%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook:
%    /Users/HershYesh/Documents/MATLAB/filesForMATLABCentral/Data.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2015/03/14 16:18:55

%% Import the data
[~, ~, raw] = xlsread('/Users/HershYesh/Documents/MATLAB/filesForMATLABCentral/Data.xlsx','Sheet1');
raw = raw(2:end,:);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[4,5,6]);
raw = raw(:,[1,2,3]);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
ID = data(:,1);
Dose = data(:,2);
Response = data(:,3);
Tmt = cellVectors(:,1);
Age = cellVectors(:,2);
Gender = cellVectors(:,3);

%% Clear temporary variables
clearvars data raw cellVectors;